### PR TITLE
Run eslint against `board_front.js`.

### PR DESCRIPTION
**Pull request by tomprince**
Most of the fixes were fairly obvious. The few that weren't, I separated into a separate commit, that can be reviewed individually.

### CODE REVIEW

**Comment by tomprince** [comment]
I did this, since I was working on #145, and wanted to be able to easily import the code from `board_front.js`.

**Comment by resonant-gamedesign** [comment]
This looks OK to me.
I prefer the old method of having growthicons have unique names and then assigning them at the end of the block. I think it is more readable. But I'm not going to bother to change it back.

**Comment by resonant-gamedesign** [comment]
This PR is bugging the board when I load anything with Growth Sets (particularly, Lure).
Some testing has shown that they don't fail in all cases, but some.

**Comment by resonant-gamedesign** [comment]
I made a change that shows up here (https://github.com/tomprince/spirit-island-builder/tree/lint-board-front), but not in this PR. Error was caused by a function that I'm not using right now, so I commented it out.

**Comment by tomprince** [comment]
> I made a change that shows up here (https://github.com/tomprince/spirit-island-builder/tree/lint-board-front), but not in this PR. Error was caused by a function that I'm not using right now, so I commented it out. If someone can get that change to show up here, I'm good with it.

It does show up for me. I'm guessing you had the PR open, and the "files" tab had a "refresh" button that would have updated it.

**Pull request merged**
