### PR TITLE
Improve the instructions popup.

### PR DESCRIPTION
**Pull request by tomprince**
- Simplify the javascript associated with the instructions popup.
  - Use a svelte binding, rather than looking up elements by id.
  - Use `document.addListener` rather to capture mouse events mouse events.
- Simplify CSS for instructions popup.
- Preserve size and position of instructions popup when closed.
- Make instructions fixed relative to the window rather than the document.
- Add link to view the instructions in a new tab.
- Ensure that the instruction popup can't be dragged offscreen.
- Prevent selecting text in the popup header.
  - Since clicking on it will move the popup, also selecting text while you do so is confusing.
- Use pointer events, rather than mouse events for dragging.
  - This should work better on mobile.
  - Use pointer capture to ensure that dragging works well over the preview frame.
- Use a `<dialog>` for instructions popup.

I think this addresses all but the second point from #52.

### CODE REVIEW

**Comment by tomprince** [comment]
(I accidentally broke the buttons while fixing the dragging, but everything should be working now).

**Comment by resonant-gamedesign** [comment]
Not sure if this bug is new, but:
image
It cuts off the table, regardless of the size.
Wondering if a bottom scroll also makes sense?

**Comment by resonant-gamedesign** [comment]
Also, when I open the Examples modal, this appears on top. I think it should be behind that modal. Is that possible?

**Comment by neubee** [comment]
> Not sure if this bug is new, but: It cuts off the table, regardless of the size. Wondering if a bottom scroll also makes sense?

Not new, I've never been able to figure out why it does that. HTML tables can be a pain. There is a horizontal scroll bar for each table, but you need to scroll to the bottom of the table to see it. #205 might improve the situation, but the tables will always be annoying when the window is small. A better option might be to use images (that you could then click on to expand) instead of text tables, or maybe just make the table font size smaller.

**Comment by neubee** [comment]
> Also, when I open the Examples modal, this appears on top. I think it should be behind that modal. Is that possible?

Yes, you just need to change the `z-index` of the other modals. I set the `z-index` of this popup to 999 when first making this because we didn't have any other popup type components.

**Comment by tomprince** [comment]
> Not sure if this bug is new, but: image It cuts off the table, regardless of the size. Wondering if a bottom scroll also makes sense?

These both appear to be existing issues, so I'd be inclined to leave them to a followup. Note that it appears that the tables themselves can scroll horizontally.

**Comment by tomprince** [comment]
> Also, when I open the Examples modal, this appears on top. I think it should be behind that modal. Is that possible?

I've fixed this in #238 by using `<dialog>` for examples.

**Comment by tomprince** [comment]
@neubee Anything preventing this from landing?

**Comment by neubee** [comment]
I seem to have found an existing bug when resizing the instructions. When decreasing the size of the instructions window, the thing can get "stuck" in a state where the size will no longer decrease but can still be increased. It seems to be related to the speed of the dragging motion when decreasing the size, if you're going slowly you won't see the bug.


https://user-images.githubusercontent.com/4044095/219054801-dea4e5dc-8cb3-4371-9c76-e1c990cb07b1.mp4


Any chance a fix for that could be included in this PR?

**Comment by tomprince** [comment]
> I seem to have found an existing bug when resizing the instructions. When decreasing the size of the instructions window, the thing can get "stuck" in a state where the size will no longer decrease but can still be increased. It seems to be related to the speed of the dragging motion when decreasing the size, if you're going slowly you won't see the bug.
> 
> Any chance a fix for that could be included in this PR?

It looks like this is probably a bug in chrome. Specifically, while resizing, if the pointer ends up over the instructions iframe, the iframe captures the pointer events, causing the drag to be interrupted. I'm not sure if there is a way to fix this.

**Comment by tomprince** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1416604 for the chrome issue.

**Comment by neubee** [comment]
That makes sense. I usually test on firefox so that explains why I hadn't noticed the issue before. Thanks for filling the chrome issue.

**Pull request merged**
