### PR TITLE
Fix handling of URLs when loading files.

### LINKED ISSUE #234: Cannot open files anymore
I have some files that I saved a week ago. I used to be able to open them, but I tried today and I couldn't. Not sure what info could be useful to provide to debug.

### LINKED ISSUE #235: BUG: 'Load' from HTML file functionality broken for Spirit Board Play Side
When pressing "Load" and selecting a previously saved spirit file, the data fails to load into the template for the Spirit Board Play Side. The other tabs (Lore Side, Power Cards, etc.) seem to work just fine when loading from a save. 

I cloned the project to see if I could fix this issue myself and raise a PR, but I am unfamiliar with Svelte so figured I would at least try to provide a detailed bug report instead. I wasn't sure if this is the same issue reported as #234, so I made a new issue. Feel free to close/combine if needed. 

---

The failure seems to be caused by loading spirit files that use one of the Example Banner assets: 
```
Uncaught (in promise) TypeError: URL constructor: /template/MyCustomContent/BannerExamples/banner-fractalmist.png is not a valid URL.
    maybeResolveURL lib.js:328
    readHTML index.svelte:361
    loadHTMLFromURL index.svelte:155
    handleInput load-button.svelte:16
```

**As a workaround,** manually removing all instances of the path `/template/MyCustomContent/BannerExamples/banner-fractalmist.png` from the exported HTML files fixed the issue for me--the other data loaded just fine after that.

### PR DESCRIPTION
**Pull request by tomprince**
When loading from a file (as opposed to an example), the base URI will be a `blob:` URL. We can't have relative URLs based on those, so just return the given (possibly relative) URL in that case.

Fixes #235. Fixes #234.

### CODE REVIEW

**Comment by resonant-gamedesign** [comment]
I'm not sure this fixed the problem, and it also caused a new one.
When I compiled, it didn't load the default banner or image for the default spirit.
image

Did I compile it wrong?

**Comment by resonant-gamedesign** [comment]
Seems like the fix is just to update all the examples... hold on.

**Comment by resonant-gamedesign** [comment]
Ok, I've updated about half the examples so they work with the 'new' way.
I'm worried about what'll happen if folks try to use old files?

**Comment by resonant-gamedesign** [comment]
This doesn't solve all users problems (see Discord) but lets push this out so that future problems are prevented (as it does solve those). @neubee 
I don't want more folks making bad boards.

**Comment by neubee** [comment]
What is up with the formatting on these HTML files, prettier is screwing up somehow.

@resonant-gamedesign Is this going to cause conflicts with the template? The examples you changed aren't proper html files now and won't work correctly if you open them with a browser, so they are diverging from the example files in the template repo. I can merge anyway and we can follow up later if needed.

**Comment by resonant-gamedesign** [comment]
The example files don't have the javascript ontop that would let them run
as a template file. I can go back and add those manually later.

**Comment by tomprince** [comment]
> Seems like the fix is just to update all the examples... hold on.

No, that is not the correct fix. It looks like I messed up the conditional when I was refactoring. I've reverted the change to the examples and fixed the error in #240.

**Comment by resonant-gamedesign** [comment]
Dang I liked the new examples. Maybe I can still access those files?

**Comment by neubee** [comment]
> Dang I liked the new examples. Maybe I can still access those files?

You can browse the repo from that commit (with the examples you changed) at https://github.com/neubee/spirit-island-builder/tree/dddf58c2eb1f28814ac7edd1382edd553a16e223

**Comment by resonant-gamedesign** [comment]
Can I download in bulk?

**Comment by neubee** [comment]
Yes, but then you would be downloading another copy of the repo (not a big deal, you just grab the files you want and then delete the rest).

A better way would be to run `git checkout dddf58c2eb1f28814ac7edd1382edd553a16e223` in your terminal. That will put you on the commit with the changed files which you could then browse in your editor (and then when you're done you just checkout whatever branch you want to switch back to).

**Pull request merged**
