### PR TITLE
dom-to-image-more

### PR DESCRIPTION
**Pull request by Donkid33**
Implemented Dom to Image more rather than HTML2Canvas.

It works like a charm! :)

### CODE REVIEW

**Comment by resonant-gamedesign** [comment]
@neubee any reason why the status check isn't clearing on this one? I'm ready to push it to dev.

**Comment by neubee** [comment]
Seems like we're no longer using the html2canvas package at all, correct? If so, it should be removed from package.json

**Comment by neubee** [comment]
> @neubee any reason why the status check isn't clearing on this one? I'm ready to push it to dev.

This is the same issue we had with Tom. Cloudflare can't build from other folk's repos. Change the base (the branch that we're merging into) to `dom-to-image`, then you can merge, then make a PR merging `dom-to-image` into `dev` and all the checks will run.

**Comment by resonant-gamedesign** [comment]
I really don't know what this means. And is this something I can do, or
Lemurkin?

**Pull request merged**
