### PR TITLE
Use `white-space: pre-line` to presvere line-breaks.

### PR DESCRIPTION
**Pull request by tomprince**
I turns out that CSS has a native way of preserving line-breaks using CSS. This switches everything but power-cards to use that, replacing the javascript that did that manually. This generates slightly different HTML, as it doesn't wrap each source line in a `div`, but it appears to generate identical output.

This doesn't change the power-cards, as the relevant text is in a flexbox container where removing the `div`s causes layout change.

### CODE REVIEW

**Comment by resonant-gamedesign** [comment]
I'm having trouble checking out your PRs. @neubee I can't switch to this (and other) PRs in VSCode. Any guesses?

**Comment by resonant-gamedesign** [comment]
Ok, Playing with it.
Having issues with example spirit. On page load, it looks like this:
image
When I later load new spirits, they seem to look OK. Thoughts?

**Comment by tomprince** [comment]
I'm guessing that is a side-effect of https://github.com/neubee/spirit-island-builder/blob/eb163ad914fb5a8e07acc1bfbb39d02c8d0ba4ad/src/routes/spirit-board/index.svelte#L393
I don't see that when using the load button to load the demo file, or when using #180.

**Comment by tomprince** [comment]
(And I think the solution to compatibility with templates should be using `readHTML` and #145 for use from templates as well).

**Comment by resonant-gamedesign** [comment]
> (And I think the solution to compatibility with templates should be using `readHTML` and #145 for use from templates as well).

Can you give a little more context to this statement?

**Comment by resonant-gamedesign** [comment]
> I'm guessing that is a side-effect of
> 
> https://github.com/neubee/spirit-island-builder/blob/eb163ad914fb5a8e07acc1bfbb39d02c8d0ba4ad/src/routes/spirit-board/index.svelte#L393
> 
> 
> I don't see that when using the load button to load the demo file, or when using #180.

Ok. Is there any way for me to test both branches together?
Or maybe we can get #180 resolved and circle back. I think it got worse since yesterday, which doesn't make sense:
Volcano_Looming_High_SpiritBoard (5)

**Comment by neubee** [comment]
@resonant-gamedesign You can test them together. You need to merge branch generate-html from Tom's repo into this branch (or vice versa). You would checkout this branch locally, perform the merge, and then test (and then revert your changes if needed). Or, if #180 is ready to go I can merge it into dev but it looks like there is still an issue to work out.

**Comment by resonant-gamedesign** [comment]
My issues with this were resolved. I'm good with this.
@neubee

**Pull request merged**
