### PR TITLE
Specify font for page title

### PR DESCRIPTION
**Pull request by neubee**

### CODE REVIEW

**Comment by neubee** [comment]
@resonant-gamedesign Do you still need this change, or are the fonts OK?

**Comment by resonant-gamedesign** [comment]
I'm not sure I know what to do with this change. Where do I put the font? I
want the title to be Lato

**Comment by neubee** [comment]
What exactly do you mean by the "title"?

**Comment by resonant-gamedesign** [comment]
"The spirit island builder"

**Comment by resonant-gamedesign** [comment]
To clarify, I don't think Lato is included with the project... its in the template, but I don't think this can access those files... right?

**Comment by neubee** [comment]
Understood, I didn't realize that I had lato installed on my system. I've updated the PR to use the lato fonts that are located with the template.

**Pull request merged**
