### PR TITLE
Remove margins on preview frame body.

### PR DESCRIPTION
**Pull request by tomprince**
These boards cause the preview frame to needlessly scroll a tiny amount for me.

### CODE REVIEW

**Comment by neubee** [comment]
@resonant-gamedesign let me know if you have any problems with this change. If not I'll merge it.

**Comment by resonant-gamedesign** [comment]
I'd like the keep the top margin. Is there a different workaround?
The scrollbars haven't been coming up for me, so I can't test it. Perhaps we just need to make the iframe a little larger?

**Comment by tomprince** [comment]
What is the reason for wanting a top margin?

**Comment by resonant-gamedesign** [comment]
> What is the reason for wanting a top margin?

Template. Looks better with some distance from the top of the screen.

**Comment by resonant-gamedesign** [comment]
Alright, nvm go ahead and accept it.

**Comment by tomprince** [comment]
Once (or if) #180 lands, it would be possible to write some CSS in such a way that it only applies in that things aren't being shown in the preview frame. (Though it would take some amount of manual work to get things to the point where anything reasonable is being displayed, outside of the app.)

**Comment by tomprince** [comment]
Although, I guess in that case, you could just even just have an additional non-app css file that adds whatever margin is appropriate to the body.

**Comment by resonant-gamedesign** [comment]
@neubee lets push this to dev

**Pull request merged**
