### PR TITLE
Footer improvements.

### LINKED ISSUE #223: Move footer to bottom of page
And I think they're wider than before?
image

### PR DESCRIPTION
**Pull request by tomprince**
- Make footer always be at the bottom of the window. (fixes #223)
- Move page footer to a separate component.
- Use hand-written styles for footer.
- Set noreferrer on footer links.

### CODE REVIEW

**Comment by resonant-gamedesign** [comment]
this seems fine. I'm not sure what the hand-written style is. I don't see it anywhere.

**Comment by tomprince** [comment]
> I'm not sure what the hand-written style is. I don't see it anywhere.

It is using styles included at the end of the component, rather than using styles from bulma.

**Comment by resonant-gamedesign** [comment]
Hahaha I totally misunderstood hand-written!

**Comment by resonant-gamedesign** [comment]
Looks good @neubee

**Pull request merged**
