### PR TITLE
Use `<dialog>` for examples modal.

### PR DESCRIPTION
**Pull request by tomprince**
This is stacked on #237 since there is a trivial conflict (due to indenting).

### CODE REVIEW

**Comment by resonant-gamedesign** [comment]
The image files aren't showing up for me. Maybe its because the 'stacked' thing?

**Comment by tomprince** [comment]
> The image files aren't showing up for me. Maybe its because the 'stacked' thing?

It was because I incorrectly rebased this on top of #237. (Specifically, I accidentally dropped the changes introduced there to show the images when resolving the conflict between the two bits of code). It should be fixed now.

**Comment by resonant-gamedesign** [comment]
I might have messed this one up with that merge I did?

**Comment by resonant-gamedesign** [comment]
@neubee this one looks good

**Pull request merged**
