### PR TITLE
Some minor UI and svelte improvements.

### PR DESCRIPTION
**Pull request by tomprince**
- Use loops in a few more places (tab bar, power card element selector). This makes it easier to update how these are displayed.
- Remove some svelte if statements that were displaying something in the last iteration of a loop by moving the
  contents till after the loop.
- Use buttons for selecting elements for power cards.
- Add `<header>` around the page title and tab bar.
- Get rid of the per-tab heading, as this duplicates the tab bar.
- Improve the drop-down section header:
    - Add styles for hover and focus.
    - Indicate to accessibility tools whether a section is expanded.
    - Hide the icons from accessibility.
 - Update ion-icons to the latest version. (Ideally this should come from npm, but I'll do that in a separate PR.
 
I may add more things to this, as I encounter them, but that shouldn't block merging this.

### CODE REVIEW

**Comment by neubee** [comment]
@resonant-gamedesign This PR makes a few minor visual changes. Once you've reviewed I'll get it merged.

**Comment by resonant-gamedesign** [comment]
Again, having trouble testing PRs from Tom. sorry about the wait

**Comment by resonant-gamedesign** [comment]
Looks good. I think I'd like to work on the hover over the component expansion panels, but that can be for a future PR! Great work.

**Comment by tomprince** [comment]
> Looks good. I think I'd like to work on the hover over the component expansion panels, but that can be for a future PR! Great work.

As I mentioned in https://github.com/neubee/spirit-island-builder/pull/159#issuecomment-1374814204, bulma doesn't appear to have great accessibility support, so I think it might be worthwhile to switch away from that (which would mean reworking most of the UI css and styling). I've got several WIP branches experimenting with different approaches. Some of the changes here were actually motivated by that work, removing a bunch of repetitive code to make switching to a different CSS framework easier (since there will be less places to change).

**Pull request merged**
